"""empty message

Revision ID: 088bd9b57b42
Revises: 1f142754a8f9
Create Date: 2019-05-28 12:24:46.244816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088bd9b57b42'
down_revision = '1f142754a8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trans_state_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trans_state_table',
    sa.Column('transitions_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state_tr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['state_tr_id'], ['state.id'], name='trans_state_table_state_tr_id_fkey'),
    sa.ForeignKeyConstraint(['transitions_id'], ['transition.id'], name='trans_state_table_transitions_id_fkey'),
    sa.PrimaryKeyConstraint('transitions_id', 'state_tr_id', name='trans_state_table_pkey')
    )
    # ### end Alembic commands ###
