"""empty message

Revision ID: 0e237c57ea81
Revises: 4ca79ded44ee
Create Date: 2019-05-27 13:33:23.165323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e237c57ea81'
down_revision = '4ca79ded44ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prev_state_state_id_fkey', 'prev_state', type_='foreignkey')
    op.drop_column('prev_state', 'state_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prev_state', sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('prev_state_state_id_fkey', 'prev_state', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###
