"""empty message

Revision ID: 1cd71ffe2c7b
Revises: c179ef001e7d
Create Date: 2019-05-28 11:27:52.109439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd71ffe2c7b'
down_revision = 'c179ef001e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trans_state_table_transitions_id_fkey', 'trans_state_table', type_='foreignkey')
    op.create_foreign_key(None, 'trans_state_table', 'transition', ['transitions_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trans_state_table', type_='foreignkey')
    op.create_foreign_key('trans_state_table_transitions_id_fkey', 'trans_state_table', 'state', ['transitions_id'], ['id'])
    # ### end Alembic commands ###
