"""empty message

Revision ID: 1f142754a8f9
Revises: a9ad83f827b4
Create Date: 2019-05-28 12:13:54.585469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f142754a8f9'
down_revision = 'a9ad83f827b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trans_state_table',
    sa.Column('transitions_id', sa.Integer(), nullable=False),
    sa.Column('state_tr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_tr_id'], ['state.id'], ),
    sa.ForeignKeyConstraint(['transitions_id'], ['transition.id'], ),
    sa.PrimaryKeyConstraint('transitions_id', 'state_tr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trans_state_table')
    # ### end Alembic commands ###
