"""empty message

Revision ID: 4ca79ded44ee
Revises: fe0fe6664ebe
Create Date: 2019-05-25 18:58:55.086318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca79ded44ee'
down_revision = 'fe0fe6664ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state', sa.Column('prev_states_id', sa.Integer(), nullable=True))
    op.add_column('state', sa.Column('transitions_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'state', 'transition', ['transitions_id'], ['id'])
    op.create_foreign_key(None, 'state', 'state', ['prev_states_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='foreignkey')
    op.drop_constraint(None, 'state', type_='foreignkey')
    op.drop_column('state', 'transitions_id')
    op.drop_column('state', 'prev_states_id')
    # ### end Alembic commands ###
