"""empty message

Revision ID: 5f22cd0e5b2b
Revises: 18cceeb093a7
Create Date: 2019-05-22 18:27:31.401425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f22cd0e5b2b'
down_revision = '18cceeb093a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition'], ['condition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transitions', sa.Integer(), nullable=True),
    sa.Column('prev_states', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prev_states'], ['state.id'], ),
    sa.ForeignKeyConstraint(['transitions'], ['transition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state')
    op.drop_table('transition')
    op.drop_table('description')
    op.drop_table('condition')
    # ### end Alembic commands ###
