"""empty message

Revision ID: 707d5ca1b4bd
Revises: 1cd71ffe2c7b
Create Date: 2019-05-28 11:36:51.914347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707d5ca1b4bd'
down_revision = '1cd71ffe2c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('state_transitions_id_fkey', 'state', type_='foreignkey')
    op.drop_constraint('state_prev_states_id_fkey', 'state', type_='foreignkey')
    op.drop_column('state', 'transitions_id')
    op.drop_column('state', 'prev_states_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state', sa.Column('prev_states_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('state', sa.Column('transitions_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('state_prev_states_id_fkey', 'state', 'state', ['prev_states_id'], ['id'])
    op.create_foreign_key('state_transitions_id_fkey', 'state', 'transition', ['transitions_id'], ['id'])
    # ### end Alembic commands ###
