"""empty message

Revision ID: c22f33bb1140
Revises: 5f22cd0e5b2b
Create Date: 2019-05-22 18:28:35.234320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22f33bb1140'
down_revision = '5f22cd0e5b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition', sa.Column('next_state', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transition', 'state', ['next_state'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transition', type_='foreignkey')
    op.drop_column('transition', 'next_state')
    # ### end Alembic commands ###
