"""empty message

Revision ID: ddd8ab94e4a9
Revises: fbf18fd1667a
Create Date: 2019-05-27 16:55:14.623104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd8ab94e4a9'
down_revision = 'fbf18fd1667a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state', 'prev_states_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('state', 'transitions_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state', 'transitions_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('state', 'prev_states_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
