"""empty message

Revision ID: e0de25225847
Revises: 0e237c57ea81
Create Date: 2019-05-27 16:17:51.916662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0de25225847'
down_revision = '0e237c57ea81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prev_state')
    op.drop_table('trans_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trans_state',
    sa.Column('transitions_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transition_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transition_id'], ['transition.id'], name='trans_state_transition_id_fkey'),
    sa.ForeignKeyConstraint(['transitions_id'], ['state.id'], name='trans_state_transitions_id_fkey')
    )
    op.create_table('prev_state',
    sa.Column('prev_states_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prev_states_id'], ['state.id'], name='prev_state_prev_states_id_fkey')
    )
    # ### end Alembic commands ###
